const COLOR = {
  PRIMARY: '#0062FF',
  SECONDARY: '#171725',
  BACKGROUND: '#FFFFFF',

  TEXT_GRAY_LIGHT: '#B5B5BE',
  TEXT_GRAY_DARK: '#92929D',

  PROGRESS_BACKGROUND: '#E2E2EA',

  BORDER: '#D5D5DC',
  BORDER_BOTTOM_BAR: '#E2E2EA',
  NOTI: '#FC5A5A',
};

export default COLOR;
